"""Assign categories and write data/projects.js + data/advice.js for the site.

Run after clean_data.py and enrich_github.py (from the scripts/ folder).
"""
import json, re
from pathlib import Path

DATA = Path(__file__).resolve().parent.parent / "data"
CATEGORIES = [  # first match wins
    ("Game", r"\b(game|unity|phaser|platformer|shooter)\b"),
    ("AI / Machine Learning", r"\b(ai|openai|machine learning|model|predict|forecast|llm|gpt|pytorch|tensorflow)\b"),
    ("Data & Research", r"\b(data analysis|analysis|research|survival|pandas|visualization|inflation)\b"),
    ("Security", r"\b(security|integrity|vulnerab)"),
    ("Mobile", r"\b(android|ios|react native|flutter|mobile)\b"),
    ("Campus & Community", r"\b(brooklyn college|campus|cuny|isso|student|cis connect)\b"),
    ("Web App", r"\b(web|react|next\.js|vue|angular|node|express|full-stack|website)\b"),
]

projects = json.load(open(DATA / "projects.json"))
advice = json.load(open(DATA / "advice.json"))
for p in projects:
    hay = " ".join(filter(None, [p.get("title"), p.get("description"), p["repo"], " ".join(p["languages"])])).lower()
    p["category"] = next((c for c, rx in CATEGORIES if re.search(rx, hay)), "Other") if p.get("title") else "Video demo"
    p.pop("majors", None); p.pop("readme_found", None)

def write_js(name, var, obj):
    body = json.dumps(obj, indent=2, ensure_ascii=False)
    (DATA / name).write_text(f"// Generated by scripts/build_data.py. Edit the JSON source and re-run instead.\nconst {var} = {body};\n")

write_js("projects.js", "PROJECTS", projects)
write_js("advice.js", "ADVICE", advice)
print(f"Wrote {len(projects)} projects and {len(advice)} advice quotes")
