// Generated by scripts/build_data.py. Edit the JSON source and re-run instead.
const PROJECTS = [
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/HenryC0416/vulnewdata",
    "video": null,
    "members": [
      "Henry Chen"
    ],
    "id": "p001",
    "title": "Vulnewdata",
    "description": null,
    "languages": [],
    "category": "Other"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/YaArsen/CISC.4900-Recipe-Management-Repository",
    "video": null,
    "members": [
      "Arsen Yakubyants"
    ],
    "id": "p002",
    "title": "Recipe Management Repository",
    "description": null,
    "languages": [],
    "category": "Other"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/dabin-tang/rate-my-spot",
    "video": null,
    "members": [
      "Da Bin Tang"
    ],
    "id": "p003",
    "title": "Rate My Spot",
    "description": "Rate My Spot is a platform for discovering spots, sharing experiences, and building social connections. It consists of two parts:",
    "languages": [
      "React",
      "Node",
      "Java",
      "TypeScript",
      "MySQL",
      "Spring Boot"
    ],
    "category": "Web App"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": null,
    "video": null,
    "members": [
      "Emersen Bribiesca"
    ],
    "id": "p004",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/JoshuaDrysdale/4900-project",
    "video": null,
    "members": [
      "Kevin Ni",
      "Joshua Drysdale"
    ],
    "id": "p005",
    "title": "RHA — Ride-Hailing Aggregator",
    "description": "RHA is a web application that allows users to plan rides by setting pickup and dropoff locations, view driving routes, and will eventually compare prices across multiple ride-hailing services (Uber, Lyft, etc.) in one place. Deployment of certain technologies will be considered.",
    "languages": [
      "Node",
      "Express",
      "JavaScript",
      "PostgreSQL",
      "Supabase"
    ],
    "category": "Web App"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/shaoru0302/CISC4900",
    "video": null,
    "members": [
      "Jiexian He",
      "Zhihui Gan",
      "Shaoru Wu-Zhu"
    ],
    "id": "p006",
    "title": "BeautyNest E-commerce Website Project",
    "description": "BeautyNest is a lightweight full-stack e-commerce website designed for selling essential oil jewelry and handcrafted products created by the business itself.",
    "languages": [
      "Node",
      "JavaScript",
      "MySQL"
    ],
    "category": "Web App"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/futurelegend1/MoneyTrack",
    "video": null,
    "members": [
      "Jerry Gao",
      "Sheng Lin"
    ],
    "id": "p007",
    "title": "MoneyTrack",
    "description": "MoneyTrack is a personal finance web application that helps users track and manage their expenses. The application allows users to create an account, log in securely, and record their spending in an organized way. The goal of MoneyTrack is to provide a simple and clean interface that helps users better understand…",
    "languages": [
      "React",
      "JavaScript",
      "TypeScript",
      "Firebase",
      "Tailwind"
    ],
    "category": "Web App"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/Sulaymaann/CSAProjectDashboard4900",
    "video": null,
    "members": [
      "Sulaymaan Hashmie"
    ],
    "id": "p008",
    "title": "Csaproject Dashboard",
    "description": null,
    "languages": [],
    "category": "Other"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/ssshz-n/4900ResumeAnalysis",
    "video": "https://drive.google.com/file/d/1LaXI98q_ZGKvqRXzj7HMzejDjozwKDj9/view?usp=sharing",
    "members": [
      "XinLing Sun",
      "Niki Lin"
    ],
    "id": "p009",
    "title": "Smart Resume Analyzer & Career Advisor",
    "description": null,
    "languages": [
      "Java",
      "JavaScript",
      "Supabase",
      "Tailwind",
      "Spring Boot"
    ],
    "category": "Other"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/muhammadn63/StudyWithAI",
    "video": "https://drive.google.com/file/d/1yiKcGUVwj7p0h3sdtrt5caecC-B7G7oc/view?usp=sharing",
    "members": [
      "Muhammad Numan"
    ],
    "id": "p010",
    "title": "StudyWithAI",
    "description": null,
    "languages": [
      "Node",
      "Express",
      "JavaScript",
      "MongoDB",
      "OpenAI"
    ],
    "category": "AI / Machine Learning"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/jellyfishing2346/grumpy-gamer",
    "video": "https://www.youtube.com/watch?v=wnItXCi3VQ0",
    "members": [
      "Faizan Khan"
    ],
    "id": "p011",
    "title": "Grumpy Gamer",
    "description": "Teaching AI to rage-quit less than humans (eventually)",
    "languages": [
      "React",
      "FastAPI",
      "Python",
      "TypeScript",
      "PostgreSQL",
      "Docker"
    ],
    "category": "AI / Machine Learning"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": null,
    "video": null,
    "members": [
      "Jessica Livchits"
    ],
    "id": "p012",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/PinkSheep27/SmartTrip",
    "video": null,
    "members": [
      "Ivan Rudik"
    ],
    "id": "p013",
    "title": "SmartTrip",
    "description": "A travel booking system that consolidates multiple travel services into a single platform using TypeScript, React, Tailwind, Supabase and it's accompanying services.",
    "languages": [
      "React",
      "Next.js",
      "Node",
      "TypeScript",
      "Supabase",
      "AWS"
    ],
    "category": "Web App"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/RogueJunny/4900-project",
    "video": "https://1drv.ms/v/c/8f0f4f78b1ee37f8/IQAqqPjeCbr9RZCck3O3HWA5ARiCmx3AbjKqH_Fj2L1nIwg?e=RAxbeh",
    "members": [
      "Sammy Sharif",
      "Junliang Lei"
    ],
    "id": "p014",
    "title": "Brooklyn College CIS Connect (Spring 2026)",
    "description": "For our CISC 4900 project, we will be maintaining and updating the Brooklyn College CIS Connect Website with supervision from Fendja Larivaux.",
    "languages": [],
    "category": "Campus & Community"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/ashantib102/CodeLabRevival",
    "video": null,
    "members": [
      "Ashanti Benons",
      "Daphne Gray"
    ],
    "id": "p015",
    "title": "CodeLab Revival",
    "description": null,
    "languages": [
      "React",
      "Next.js",
      "FastAPI",
      "TypeScript",
      "PostgreSQL",
      "Tailwind"
    ],
    "category": "Web App"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/mubasshirm22/bcsinghlab",
    "video": null,
    "members": [
      "Mubasshir Mumtaz"
    ],
    "id": "p016",
    "title": "Secondary Structure Prediction Display - Browser Version",
    "description": "An application that sends a protein sequence to various websites to generate predictions. The results are then scraped and saved into a database that is accessed for display.",
    "languages": [
      "Flask",
      "Python"
    ],
    "category": "Other"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/Ssalem1235/Independent-Group-Study-CISC4900",
    "video": null,
    "members": [
      "Saleh Salem",
      "Saisha Wesley"
    ],
    "id": "p017",
    "title": "Independent Group Study",
    "description": "This project investigates how the rapid adoption of Artificial Intelligence (AI) affects human society and the environment. Using publicly available, reputable datasets, we conduct a data-driven analysis of AI adoption trends, societal impact indicators, and energy consumption associated with AI-driven data…",
    "languages": [
      "Python",
      "Pandas"
    ],
    "category": "AI / Machine Learning"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/huscse/navis-extended-cisc4900",
    "video": "https://www.loom.com/share/681f85010f794a319793e9a32a90bad4",
    "members": [
      "Husnain Khaliq"
    ],
    "id": "p018",
    "title": "NAVIS-Extended",
    "description": null,
    "languages": [
      "Next.js",
      "FastAPI",
      "Python",
      "PostgreSQL",
      "Docker"
    ],
    "category": "Web App"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/J-Koral/cpu-scheduling-simulator",
    "video": null,
    "members": [
      "Jonathan Koral"
    ],
    "id": "p019",
    "title": "Cpu Scheduling Simulator",
    "description": null,
    "languages": [],
    "category": "Other"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": null,
    "video": null,
    "members": [
      "Jianyong Li"
    ],
    "id": "p020",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/Gazwahi/CISC_4900FinalProject-Juan-John",
    "video": null,
    "members": [
      "Gazwah Ishtiaq"
    ],
    "id": "p021",
    "title": "Final Project Juan John",
    "description": null,
    "languages": [
      "Java",
      "JavaScript",
      "PostgreSQL",
      "Spring Boot"
    ],
    "category": "Other"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/yevexe/RenderDeck",
    "video": null,
    "members": [
      "George Grammatosis"
    ],
    "id": "p022",
    "title": "RenderDeck",
    "description": "A browser-based 3D rendering application built with Three.js for creating, customizing, and previewing 3D models with PBR (Physically Based Rendering) materials.",
    "languages": [
      "Java",
      "PostgreSQL",
      "Supabase",
      "Three.js",
      "Spring Boot"
    ],
    "category": "Other"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/Lunaris47/shopping-list-app",
    "video": null,
    "members": [
      "Jesse Sciamanna"
    ],
    "id": "p023",
    "title": "Shopping List App (Android)",
    "description": "An Android application that allows users to create, manage, and organize shopping lists, similar in concept to Google Keep.",
    "languages": [
      "Java",
      "Android"
    ],
    "category": "Mobile"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": null,
    "video": "https://www.youtube.com/watch?v=ZtjowxVXte4",
    "members": [
      "Meiling You"
    ],
    "id": "p024",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/ZibiAQ/Plueprint-4900",
    "video": null,
    "members": [
      "Aoqing Chen"
    ],
    "id": "p025",
    "title": "Plueprint",
    "description": null,
    "languages": [
      "Python"
    ],
    "category": "Other"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/annabelenko/CISC4900",
    "video": null,
    "members": [
      "Anna Belenko",
      "Luis Gonzalez"
    ],
    "id": "p026",
    "title": "Accessibility Platformer (Phaser 3)",
    "description": "A 2D educational platformer built with Phaser 3 about disability and accessibility on a college campus. Players navigate two scenes — a security checkpoint and a classroom — collecting quiz tokens that trigger AI-generated accessibility questions powered by a RAG pipeline backed by Google Gemini. Features tunnel…",
    "languages": [
      "Node",
      "FastAPI",
      "Python",
      "Phaser"
    ],
    "category": "Game"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/YishayHarel/unified-market",
    "video": null,
    "members": [
      "Yishay Harel"
    ],
    "id": "p027",
    "title": "UnifiedMarket",
    "description": "A full-stack financial market platform with AI-powered insights, real-time stock tracking, and social investing features.",
    "languages": [
      "React",
      "Node",
      "Express",
      "TypeScript",
      "PostgreSQL",
      "Supabase"
    ],
    "category": "AI / Machine Learning"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/bc-cisc4900/inflation-tracker",
    "video": "https://drive.google.com/file/d/1EQ9_Re0Uph0hjZquGh7RMASIvb5GdBtM/view",
    "members": [
      "Gabriel Krishtul",
      "Yuan Ruan",
      "Mohamed Massoud"
    ],
    "id": "p028",
    "title": "BC-Basket (Formerly Grocery Store Inflation Tracker)",
    "description": null,
    "languages": [
      "Node",
      "JavaScript",
      "PostgreSQL",
      "Supabase"
    ],
    "category": "Data & Research"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/marz-in-flow/unphased",
    "video": null,
    "members": [
      "Marlene Novo"
    ],
    "id": "p029",
    "title": "unPhased",
    "description": "Daily Direction, Powered by Your Biology.",
    "languages": [
      "React",
      "Node",
      "Express",
      "JavaScript",
      "PostgreSQL",
      "AWS"
    ],
    "category": "Web App"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/wenlong2003/TaskFlow",
    "video": null,
    "members": [
      "Wenlong Cen Cen"
    ],
    "id": "p030",
    "title": "Task Tracker",
    "description": "Task Tracker is a full-stack web application designed to help users efficiently organize and manage their daily tasks. The application provides a simple and intuitive interface where users can create an account, securely log in, and keep track of their responsibilities in a personalized dashboard.",
    "languages": [
      "React",
      "Python",
      "MySQL"
    ],
    "category": "Web App"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/VensanDrot/ECHO_FRONT",
    "video": null,
    "members": [
      "Vensan Drot"
    ],
    "id": "p031",
    "title": "ECHO",
    "description": null,
    "languages": [],
    "category": "Other"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/senaida1097/CISC4900Project",
    "video": null,
    "members": [
      "Senaida Olivares"
    ],
    "id": "p032",
    "title": "Accessibility-Driven Web Content Production",
    "description": "This CISC4900 Project repository documents my internship project whose focus invloves web accesibility, content systems optimization, and SEO implementation for Brooklyn College website. My collaboration with the college's Marketing & Communications department includes audit, remediation, and optimization of web pages.",
    "languages": [],
    "category": "Campus & Community"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/ileanat/ReviewRadar",
    "video": null,
    "members": [
      "Munisa Ilhomova"
    ],
    "id": "p033",
    "title": "ReviewRadar",
    "description": "A community‑driven tool helping consumers cut through the noise and find genuine, trustworthy product reviews.",
    "languages": [
      "React",
      "Node",
      "Express",
      "TypeScript",
      "MongoDB",
      "Tailwind"
    ],
    "category": "Web App"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/Spulp45/cisc4900",
    "video": null,
    "members": [
      "Oliver Ruiz Diaz Benitez",
      "William Zhong"
    ],
    "id": "p034",
    "title": "Driving Stats",
    "description": "A Python app that reads and parses GPX files, stores data in a database, and displays statistics for the given data.",
    "languages": [
      "Flask",
      "Python"
    ],
    "category": "Other"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/waltermcz/nodejs-serverless-function-express",
    "video": null,
    "members": [
      "Walter Mocha"
    ],
    "id": "p035",
    "title": "Campus Sustainability AR",
    "description": "An augmented reality web app that lets students explore campus sustainability initiatives through their phone camera. Built with AR.js, A-Frame, Three.js, and deployed on Vercel.",
    "languages": [
      "React",
      "Node",
      "Express",
      "TypeScript",
      "Supabase",
      "Three.js"
    ],
    "category": "Campus & Community"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/KamaliM1/barber-appointment-fullstack",
    "video": null,
    "members": [
      "Kamali McKenzie"
    ],
    "id": "p036",
    "title": "Barber Appointment Fullstack",
    "description": null,
    "languages": [],
    "category": "Other"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/Ruqayya82/DeltaPilot-AI",
    "video": null,
    "members": [
      "Ruqayya Mustafa"
    ],
    "id": "p037",
    "title": "Trading App with Kronos-mini Predictions",
    "description": "A trading application that uses the Kronos-mini model to provide stock predictions and allows users to manage a demo trading account.",
    "languages": [
      "React",
      "Node",
      "Flask",
      "Python"
    ],
    "category": "AI / Machine Learning"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/SaifuzzamanTanim550/CISC-4900-Final-Project",
    "video": "https://drive.google.com/file/d/1zDfng6JclrgLVnXb3uxtgB2GT8cocdo9/view?usp=sharing",
    "members": [
      "Saifuzzaman Tanim"
    ],
    "id": "p038",
    "title": "BC Admissions Email Assistant",
    "description": "An AI-powered email response tool built for the Brooklyn College Office of Undergraduate Admissions. Staff paste a student inquiry, and the system automatically identifies the correct response template, fills in the student's name and semester, and returns a formatted response ready to copy into an email client.",
    "languages": [
      "React",
      "Node",
      "FastAPI",
      "Python",
      "MongoDB",
      "Docker"
    ],
    "category": "AI / Machine Learning"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/SyedIAhsan/YANA",
    "video": null,
    "members": [
      "Syed Ahsan"
    ],
    "id": "p039",
    "title": "YANA",
    "description": null,
    "languages": [],
    "category": "Other"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/RandomOscar/Personal-Finance-Budget-Forecasting-Web-Application",
    "video": null,
    "members": [
      "Oscar Chacon"
    ],
    "id": "p040",
    "title": "Personal Finance Budget Forecasting Web Application",
    "description": "This project is a full-stack personal finance web application developed as part of CISC 4900. The purpose of the application is to help users track financial activity, manage budgets, and receive financial forecasts based on historical spending behavior.",
    "languages": [
      "React",
      "FastAPI",
      "Python",
      "JavaScript",
      "PostgreSQL"
    ],
    "category": "Web App"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/Tehrim46/StyleMarket",
    "video": null,
    "members": [
      "Tehrim Iqbal",
      "Noor Fatima",
      "Tahreem Imran"
    ],
    "id": "p041",
    "title": "StyleMarket",
    "description": "StyleMarket is a web-based fashion marketplace designed to give clothing a second life through buying and selling. The platform allows users to create accounts, browse products across multiple categories, upload and manage their own listings, save products to a wishlist, manage carts, and complete purchases through…",
    "languages": [
      "JavaScript",
      "Firebase"
    ],
    "category": "Web App"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/rabia-rehmein/TALTI",
    "video": null,
    "members": [
      "Rabia Rehmein"
    ],
    "id": "p042",
    "title": "TALTI",
    "description": null,
    "languages": [
      "React",
      "TypeScript"
    ],
    "category": "Web App"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/gnailnitsuj/4900Project_Grit",
    "video": null,
    "members": [
      "Justin Liang"
    ],
    "id": "p043",
    "title": "Project Grit",
    "description": "Unity game development project for CISC 4900.",
    "languages": [
      "Unity"
    ],
    "category": "Game"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": null,
    "video": null,
    "members": [
      "Shawn Belykh"
    ],
    "id": "p044",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/eyuen62/Jump-World-the-Game-CISC4900",
    "video": null,
    "members": [
      "Edmund Yuen"
    ],
    "id": "p045",
    "title": "Jump World the Game",
    "description": "A single-player 2D pixel art platformer built in Unity 6 using C code. Developed as a senior project at Brooklyn College under CISC 4900.",
    "languages": [
      "C#",
      "Unity"
    ],
    "category": "Game"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/drod75/Lai",
    "video": null,
    "members": [
      "David Rodriguez"
    ],
    "id": "p046",
    "title": "Lai",
    "description": null,
    "languages": [
      "Python",
      "OpenAI",
      "Streamlit"
    ],
    "category": "AI / Machine Learning"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": null,
    "video": null,
    "members": [
      "Justin Tsang"
    ],
    "id": "p047",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/Jackindeng/CISC-4900-Project",
    "video": null,
    "members": [
      "Jianbin Deng"
    ],
    "id": "p048",
    "title": "Campus Second-Hand Trading Platform",
    "description": "Campus Second-Hand Trading Platform is a web-based system designed for college students to buy and sell second-hand items within the campus community. The goal of this project is to provide a simple and convenient platform where users can post products, browse available items, and manage their own listings more easily.",
    "languages": [
      "Vue",
      "Java",
      "JavaScript",
      "MySQL",
      "Spring Boot"
    ],
    "category": "Campus & Community"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/compjme/HISSOA",
    "video": null,
    "members": [
      "Rodrigo Vazquez"
    ],
    "id": "p049",
    "title": "Hissoa",
    "description": null,
    "languages": [
      "Node",
      "Android"
    ],
    "category": "Mobile"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/Fede1220/Spoty-fullstack-map",
    "video": null,
    "members": [
      "Federico Acosta"
    ],
    "id": "p050",
    "title": "Spoty",
    "description": null,
    "languages": [
      "React",
      "JavaScript",
      "PostgreSQL",
      "Supabase",
      "Tailwind"
    ],
    "category": "Web App"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/SanatjonB/wardrobe-web-app",
    "video": null,
    "members": [
      "Sanatjon Burkhanov"
    ],
    "id": "p051",
    "title": "Wardrobe Web App",
    "description": "This is a very minimalistic design of a wardrobe app you need two things a supabase acc and a resend acc",
    "languages": [
      "Supabase"
    ],
    "category": "Web App"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/Jieisj/restaurant-pos",
    "video": null,
    "members": [
      "Chaojie Ma"
    ],
    "id": "p052",
    "title": "Restaurant POS",
    "description": "Restaurant POS is a full-stack restaurant point-of-sale system built with a React/Vite frontend, a Spring Boot backend, and a MySQL database.",
    "languages": [
      "React",
      "MySQL",
      "Spring Boot"
    ],
    "category": "Web App"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/oleksiisud/movie-discovery-app",
    "video": "https://www.youtube.com/watch?v=vfms-9oZ2Bs",
    "members": [
      "Oleksii Sudarin"
    ],
    "id": "p053",
    "title": "CineMixer",
    "description": "A full-stack web application for discovering and picking movies to watch. Users enter a mix of descriptive words and CineMixer's vector-embedding search engine surfaces the most suitable films. Users with an account can save movies to a personal watchlist and mark them as watched, using watchlist's emotion…",
    "languages": [
      "Angular",
      "Node",
      "Django",
      "Python",
      "TypeScript",
      "PostgreSQL"
    ],
    "category": "Web App"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/jaren55/BTT-Grid-WiDS-Project",
    "video": null,
    "members": [
      "Jaren Taznim"
    ],
    "id": "p054",
    "title": "BTT-Grid-WiDS-Project",
    "description": "This project builds a survival analysis–based forecasting system that estimates the probability a wildfire will threaten evacuation zones within 12, 24, 48, and 72 hours, using only the first 5 hours of observed fire behavior. By producing calibrated, time-dependent risk forecasts, the system supports…",
    "languages": [
      "Python",
      "Pandas"
    ],
    "category": "Data & Research"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/EricG20/gurchin_game",
    "video": "https://www.youtube.com/watch?v=1nWiDPINJ7w",
    "members": [
      "Eric Guiteau"
    ],
    "id": "p055",
    "title": "Zorbulon Pylon Defense Force",
    "description": "Zorbulon Pylon Defense Force is a wave based Arcade shooter developed in 2 and a half weeks in for CISC 3367 (Game Design and Development).",
    "languages": [
      "Node",
      "Express"
    ],
    "category": "Game"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/MarcoB517/File-Integrity-Monitoring",
    "video": null,
    "members": [
      "Marco Buritca"
    ],
    "id": "p056",
    "title": "File Integrity Monitoring System",
    "description": "A Python-based File Integrity Monitoring (FIM) tool for detecting unauthorized or unexpected file changes within a target directory.",
    "languages": [
      "Python",
      "SQLite"
    ],
    "category": "Security"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/edmondhl/CIS_Careers_Deep_Dive",
    "video": null,
    "members": [
      "Edmond Liu"
    ],
    "id": "p057",
    "title": "CIS Careers Deep Dive",
    "description": "A data analysis and visualization project that explores tech employment trends, salary changes, and in-demand technologies across U.S. states using government-provided labor and occupation data.",
    "languages": [
      "Next.js",
      "Node",
      "Python",
      "TypeScript",
      "Tailwind",
      "Pandas"
    ],
    "category": "Data & Research"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/AbduAzim424/Monteverde-v1",
    "video": null,
    "members": [
      "Azimjon Ulmasov"
    ],
    "id": "p058",
    "title": "Monteverde V1",
    "description": null,
    "languages": [],
    "category": "Other"
  },
  {
    "semester": "S2026",
    "semester_label": "Spring 2026",
    "repo": "https://github.com/mroberts764/show-the-book-author",
    "video": null,
    "members": [
      "Michael Roberts"
    ],
    "id": "p059",
    "title": "Show The Book Author",
    "description": null,
    "languages": [],
    "category": "Other"
  },
  {
    "semester": "F2025",
    "semester_label": "Fall 2025",
    "repo": null,
    "video": null,
    "members": [
      "Anastasiia Pavlyuk"
    ],
    "id": "p060",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2025",
    "semester_label": "Fall 2025",
    "repo": null,
    "video": "https://fighterwolfmc.itch.io/opjager",
    "members": [
      "Julian Lam"
    ],
    "id": "p061",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2025",
    "semester_label": "Fall 2025",
    "repo": null,
    "video": null,
    "members": [
      "Malak Yafai"
    ],
    "id": "p062",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2025",
    "semester_label": "Fall 2025",
    "repo": null,
    "video": null,
    "members": [
      "Anonymous student"
    ],
    "id": "p063",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2025",
    "semester_label": "Fall 2025",
    "repo": null,
    "video": null,
    "members": [
      "Anonymous student"
    ],
    "id": "p064",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2025",
    "semester_label": "Fall 2025",
    "repo": null,
    "video": null,
    "members": [
      "Armand Kaloshi"
    ],
    "id": "p065",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2025",
    "semester_label": "Fall 2025",
    "repo": null,
    "video": null,
    "members": [
      "Anonymous student"
    ],
    "id": "p066",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2025",
    "semester_label": "Fall 2025",
    "repo": null,
    "video": null,
    "members": [
      "Anonymous student"
    ],
    "id": "p067",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2025",
    "semester_label": "Fall 2025",
    "repo": null,
    "video": "https://www.youtube.com/watch?v=1c2sOuXYXR8",
    "members": [
      "Miguelangel Ortega"
    ],
    "id": "p068",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2025",
    "semester_label": "Fall 2025",
    "repo": null,
    "video": null,
    "members": [
      "Kiyali Ross"
    ],
    "id": "p069",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "S2025",
    "semester_label": "Spring 2025",
    "repo": null,
    "video": "https://www.youtube.com/watch?v=meTw1ttiNJA",
    "members": [
      "Lucius Kwok"
    ],
    "id": "p070",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "S2025",
    "semester_label": "Spring 2025",
    "repo": null,
    "video": null,
    "members": [
      "Marwan Koleilat"
    ],
    "id": "p071",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "S2025",
    "semester_label": "Spring 2025",
    "repo": null,
    "video": "https://www.youtube.com/watch?v=ER5j3_lLrhw",
    "members": [
      "Muaad Alomari"
    ],
    "id": "p072",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "S2025",
    "semester_label": "Spring 2025",
    "repo": null,
    "video": null,
    "members": [
      "Moise Polycarpe"
    ],
    "id": "p073",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "S2025",
    "semester_label": "Spring 2025",
    "repo": null,
    "video": null,
    "members": [
      "Alisa Grinko"
    ],
    "id": "p074",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "S2025",
    "semester_label": "Spring 2025",
    "repo": null,
    "video": "https://www.youtube.com/watch?v=4f80PhAkiO0",
    "members": [
      "Sena Orucu",
      "Zarina Shevchenko"
    ],
    "id": "p075",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "S2025",
    "semester_label": "Spring 2025",
    "repo": null,
    "video": null,
    "members": [
      "Maxo Hilaire"
    ],
    "id": "p076",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "S2025",
    "semester_label": "Spring 2025",
    "repo": null,
    "video": null,
    "members": [
      "Ahshreyah Ross"
    ],
    "id": "p077",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "S2025",
    "semester_label": "Spring 2025",
    "repo": null,
    "video": null,
    "members": [
      "Ali Fares"
    ],
    "id": "p078",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "S2025",
    "semester_label": "Spring 2025",
    "repo": null,
    "video": null,
    "members": [
      "Arthur Movsesyan"
    ],
    "id": "p079",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "S2025",
    "semester_label": "Spring 2025",
    "repo": null,
    "video": "https://www.youtube.com/watch?v=iJ77fRr7x4A",
    "members": [
      "Fei Lin",
      "Mohammad Najm",
      "Adam Sadov"
    ],
    "id": "p080",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "S2025",
    "semester_label": "Spring 2025",
    "repo": null,
    "video": "https://www.youtube.com/watch?v=9dtt5XTWZ9k",
    "members": [
      "Samuel Rodriguez"
    ],
    "id": "p081",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "S2025",
    "semester_label": "Spring 2025",
    "repo": null,
    "video": null,
    "members": [
      "Mohamed Thabet"
    ],
    "id": "p082",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "S2025",
    "semester_label": "Spring 2025",
    "repo": null,
    "video": null,
    "members": [
      "Angie Rivera"
    ],
    "id": "p083",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "S2025",
    "semester_label": "Spring 2025",
    "repo": null,
    "video": null,
    "members": [
      "Otabek Islomjonov"
    ],
    "id": "p084",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2024",
    "semester_label": "Fall 2024",
    "repo": null,
    "video": null,
    "members": [
      "Wenyu Pang"
    ],
    "id": "p085",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2024",
    "semester_label": "Fall 2024",
    "repo": null,
    "video": null,
    "members": [
      "Zhijie Tan"
    ],
    "id": "p086",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2024",
    "semester_label": "Fall 2024",
    "repo": null,
    "video": null,
    "members": [
      "Camilo Lopez"
    ],
    "id": "p087",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2024",
    "semester_label": "Fall 2024",
    "repo": null,
    "video": null,
    "members": [
      "Ziyang Li"
    ],
    "id": "p088",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2024",
    "semester_label": "Fall 2024",
    "repo": null,
    "video": null,
    "members": [
      "Ahmed Sidahmed"
    ],
    "id": "p089",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2024",
    "semester_label": "Fall 2024",
    "repo": null,
    "video": null,
    "members": [
      "Usman Naveed"
    ],
    "id": "p090",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2024",
    "semester_label": "Fall 2024",
    "repo": null,
    "video": "https://www.youtube.com/watch?v=KZD3oIzkZm0",
    "members": [
      "Nyseer Couse"
    ],
    "id": "p091",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2024",
    "semester_label": "Fall 2024",
    "repo": null,
    "video": null,
    "members": [
      "Steven Norris"
    ],
    "id": "p092",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2024",
    "semester_label": "Fall 2024",
    "repo": null,
    "video": null,
    "members": [
      "WilliamBuryat Takahashi"
    ],
    "id": "p093",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2024",
    "semester_label": "Fall 2024",
    "repo": null,
    "video": null,
    "members": [
      "Xhuljan Tinaj"
    ],
    "id": "p094",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2024",
    "semester_label": "Fall 2024",
    "repo": null,
    "video": null,
    "members": [
      "Ahmad Baig"
    ],
    "id": "p095",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2024",
    "semester_label": "Fall 2024",
    "repo": null,
    "video": "https://www.youtube.com/watch?v=9eXdLHnuEgE",
    "members": [
      "Mikhail Nikulin"
    ],
    "id": "p096",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2024",
    "semester_label": "Fall 2024",
    "repo": null,
    "video": null,
    "members": [
      "Joel Matlala"
    ],
    "id": "p097",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2024",
    "semester_label": "Fall 2024",
    "repo": null,
    "video": null,
    "members": [
      "Sania Pervez"
    ],
    "id": "p098",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2024",
    "semester_label": "Fall 2024",
    "repo": null,
    "video": null,
    "members": [
      "Danil Ermolin"
    ],
    "id": "p099",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2024",
    "semester_label": "Fall 2024",
    "repo": null,
    "video": null,
    "members": [
      "Amir Badrudeen"
    ],
    "id": "p100",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2024",
    "semester_label": "Fall 2024",
    "repo": null,
    "video": null,
    "members": [
      "Siegfried Anthony Nacion"
    ],
    "id": "p101",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2024",
    "semester_label": "Fall 2024",
    "repo": null,
    "video": null,
    "members": [
      "Aleksandr Chamin"
    ],
    "id": "p102",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2024",
    "semester_label": "Fall 2024",
    "repo": null,
    "video": null,
    "members": [
      "Oscar Lam"
    ],
    "id": "p103",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2024",
    "semester_label": "Fall 2024",
    "repo": null,
    "video": "https://www.youtube.com/watch?v=2tSHeqIJZac",
    "members": [
      "Krishan Sapkota"
    ],
    "id": "p104",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2024",
    "semester_label": "Fall 2024",
    "repo": null,
    "video": "https://www.youtube.com/watch?v=L_AO-OxuEeA",
    "members": [
      "Jinfeng Chen"
    ],
    "id": "p105",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2024",
    "semester_label": "Fall 2024",
    "repo": null,
    "video": "https://www.youtube.com/watch?v=pAwKnXZzvsU",
    "members": [
      "Abdelrahman Amira"
    ],
    "id": "p106",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2023",
    "semester_label": "Fall 2023",
    "repo": null,
    "video": null,
    "members": [
      "Kevin Lew"
    ],
    "id": "p107",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2023",
    "semester_label": "Fall 2023",
    "repo": null,
    "video": null,
    "members": [
      "Hang Chen"
    ],
    "id": "p108",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2023",
    "semester_label": "Fall 2023",
    "repo": null,
    "video": null,
    "members": [
      "Nafisa Anzum"
    ],
    "id": "p109",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2023",
    "semester_label": "Fall 2023",
    "repo": null,
    "video": null,
    "members": [
      "Elmira Arutiynian"
    ],
    "id": "p110",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2023",
    "semester_label": "Fall 2023",
    "repo": null,
    "video": null,
    "members": [
      "Freddy Mok Ho"
    ],
    "id": "p111",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2023",
    "semester_label": "Fall 2023",
    "repo": null,
    "video": null,
    "members": [
      "Bryan Rivera"
    ],
    "id": "p112",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2023",
    "semester_label": "Fall 2023",
    "repo": null,
    "video": null,
    "members": [
      "Daniil Mitev"
    ],
    "id": "p113",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2023",
    "semester_label": "Fall 2023",
    "repo": null,
    "video": null,
    "members": [
      "Eric Galanter"
    ],
    "id": "p114",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2023",
    "semester_label": "Fall 2023",
    "repo": null,
    "video": null,
    "members": [
      "Mohammad Ilahi"
    ],
    "id": "p115",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2023",
    "semester_label": "Fall 2023",
    "repo": null,
    "video": null,
    "members": [
      "Zixian Lin"
    ],
    "id": "p116",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2023",
    "semester_label": "Fall 2023",
    "repo": null,
    "video": null,
    "members": [
      "Emily Moncerrate"
    ],
    "id": "p117",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2023",
    "semester_label": "Fall 2023",
    "repo": null,
    "video": null,
    "members": [
      "Alina Alizai"
    ],
    "id": "p118",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2023",
    "semester_label": "Fall 2023",
    "repo": null,
    "video": null,
    "members": [
      "Aida Khydyrova"
    ],
    "id": "p119",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2023",
    "semester_label": "Fall 2023",
    "repo": null,
    "video": null,
    "members": [
      "Andrew Gil"
    ],
    "id": "p120",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2023",
    "semester_label": "Fall 2023",
    "repo": null,
    "video": null,
    "members": [
      "Waras Yaqub"
    ],
    "id": "p121",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2023",
    "semester_label": "Fall 2023",
    "repo": null,
    "video": null,
    "members": [
      "Min-Chun Lo"
    ],
    "id": "p122",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2023",
    "semester_label": "Fall 2023",
    "repo": null,
    "video": null,
    "members": [
      "Antonios Chatzinikolas Georgas"
    ],
    "id": "p123",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2023",
    "semester_label": "Fall 2023",
    "repo": null,
    "video": null,
    "members": [
      "Michael Koblishvili"
    ],
    "id": "p124",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  },
  {
    "semester": "F2023",
    "semester_label": "Fall 2023",
    "repo": null,
    "video": null,
    "members": [
      "Hesham Sharafaldin"
    ],
    "id": "p125",
    "title": null,
    "description": null,
    "languages": [],
    "category": "Video demo"
  }
];
